### ISSUE TITLE
"default is not exported" when trying to recreate riot 4 quick start

### ISSUE THREAD

**Issue by planeguy** [riot/rollup-plugin-riot#105]
I've been trying to set up the riot 4 quick start using rollup, but it throws me this error. Output looks like:

```
$ rollup -c

src/main.js → stdout...
(!) Unresolved dependencies
https://rollupjs.org/guide/en#warning-treating-module-as-external-dependency
riot (imported by src\main.js, src\try-app.riot)
[!] Error: 'default' is not exported by src\try-app.riot
https://rollupjs.org/guide/en#error-name-is-not-exported-by-module-
src\main.js (2:7)
1: import * as riot from 'riot';
2: import TryApp from './try-app.riot';
          ^
3:
4: riot.component(TryApp)(document.getElementsByTagName('try-app'), { message: 'uh' });
Error: 'default' is not exported by src\try-app.riot
    at error (C:\dev\try-riot-4\node_modules\rollup\dist\rollup.js:3766:30)
    at Module.error (C:\dev\try-riot-4\node_modules\rollup\dist\rollup.js:14611:9)
    at handleMissingExport (C:\dev\try-riot-4\node_modules\rollup\dist\rollup.js:14538:21)
    at Module.traceVariable (C:\dev\try-riot-4\node_modules\rollup\dist\rollup.js:14880:17)
    at ModuleScope.findVariable (C:\dev\try-riot-4\node_modules\rollup\dist\rollup.js:13582:37)
    at Identifier.bind (C:\dev\try-riot-4\node_modules\rollup\dist\rollup.js:11415:40)
    at CallExpression.NodeBase.bind (C:\dev\try-riot-4\node_modules\rollup\dist\rollup.js:10439:31)
    at CallExpression.bind (C:\dev\try-riot-4\node_modules\rollup\dist\rollup.js:11531:31)
    at CallExpression.NodeBase.bind (C:\dev\try-riot-4\node_modules\rollup\dist\rollup.js:10443:23)
    at CallExpression.bind (C:\dev\try-riot-4\node_modules\rollup\dist\rollup.js:11531:31)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I attempted to add a export default {} to the tag, but it just throws the ES6 "can't export there" error instead.

Any ideas what I'm doing wrong (or is the rollup plugin not ready for riot 4? it seems to be....)?

Thanks!

also, I attached my code if anyone wants to take a look:
[try-riot-4.zip](https://github.com/riot/rollup-plugin-riot/files/3109078/try-riot-4.zip)

**Comment by GianlucaGuarini** [comment]
You could start using by using the latest `rollup-plugin-riot@4` version by updating your packag.json file:

```json
{
  "dependencies": {
    "riot": "^4.0.0-rc.1"
  },
  "devDependencies": {
    "@riotjs/compiler": "^4.0.0",
    "http-server": "^0.11.1",
    "rollup": "^1.10.0",
    "rollup-plugin-riot": "^4.0.0"
  },
  "scripts": {
    "js": "rollup -c",
    "start": "http-server ./dist --cors -p 12300"
  }
}

```

2 your `rollup.config.js` file was also wrong, the `output` key should be an object:

```js
import riot from 'rollup-plugin-riot';
export default {
    input: 'src/main.js',
    output: {
      format: 'umd',
      file: 'dist/main.js',
    },
    plugins: [
        riot({
            ext: 'riot'
        })
    ]
}
```
none of the issues above is a riot issue. Good luck

**Comment by planeguy** [comment]
Great! Works perfectly now. Thanks!
