### ISSUE TITLE
Crash riot compiler when using <script type="es6"> in tag file

### ISSUE THREAD

**Issue by joelchu** [riot/rollup-plugin-riot#4]
When I leave out the `type="es6"` it works fine. But that cause other issue, because eslint-riot-plugin looking at the tag to determine if its ES5 or ES6. 

Here is the error output 

     (intermediate value)(intermediate value) is not a function
    TypeError: (intermediate value)(intermediate value) is not a function
    at _loadParser (/Users/joel/Sites/EXERCISES/es6-dev-rollup-riot-demo/node_modules/rollup-plugin-riot/node_modules/riot-compiler/lib/parsers.js:54:39)
    at _compileJS (/Users/joel/Sites/EXERCISES/es6-dev-rollup-riot-demo/node_modules/rollup-plugin-riot/node_modules/riot-compiler/lib/compiler.js:441:10)
    at getCode (/Users/joel/Sites/EXERCISES/es6-dev-rollup-riot-demo/node_modules/rollup-plugin-riot/node_modules/riot-compiler/lib/compiler.js:772:10)
    at /Users/joel/Sites/EXERCISES/es6-dev-rollup-riot-demo/node_modules/rollup-plugin-riot/node_modules/riot-compiler/lib/compiler.js:921:26
    at String.replace (native)
    at /Users/joel/Sites/EXERCISES/es6-dev-rollup-riot-demo/node_modules/rollup-plugin-riot/node_modules/riot-compiler/lib/compiler.js:919:23
    at String.replace (native)
    at Object.compile (/Users/joel/Sites/EXERCISES/es6-dev-rollup-riot-demo/node_modules/rollup-plugin-riot/node_modules/riot-compiler/lib/compiler.js:885:6)
    at transform (/Users/joel/Sites/EXERCISES/es6-dev-rollup-riot-demo/node_modules/rollup-plugin-riot/dist/rollup-plugin-riot.cjs.js:32:30)
    at /usr/local/lib/node_modules/rollup/www/ROLLUP/rollup/src/utils/transform.js:18:28
    Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki

**Comment by GianlucaGuarini** [comment]
Isn't this an issue of the eslint-riot-plugin? Could you dump your tag code here so we can have a look?

**Comment by joelchu** [comment]
This has nothing to do with eslint. I am just using rollup.js / babel to transpiler the code. 

The git is here: https://github.com/joelchu/es6-dev-rollup-riot-demo

Just the usual `npm run install` then `gulp` 

just editing the `src/app/components/app.tag` with <script type="es6"> and it will crash. 

Cheers.

**Comment by GianlucaGuarini** [comment]
Well if you use babel 6 and the `es6` option it's going to be hard to get it running. Reading [our doc](http://riotjs.com/guide/compiler/#babel-6) can be a good start. Use `babel` instead of `es6`

**Comment by joelchu** [comment]
I did read the doc - this is how I know how to setup babel in the first place. anyway, it does work - the only problem is doesn't work with other tools (such as ESlint at the moment) also Testing is any issue. Guess I just have to write my own plugin for that then. Cheers.
